version: '3'
services:
  selenium-hub:
    image: selenium/hub:4.6.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=10  # Adjust this based on your need

  selenium-node-chrome1:
    image: selenium/node-chrome:4.6.0
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=10  # Set the maximum number of sessions per node
      - SE_NODE_PORT=5555
    depends_on:
      - selenium-hub
    ports:
      - "5555:5555"

  airflow-webserver:
    build:
      context: airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__FERNET_KEY=your_fernet_key
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX=True
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/db:/opt/airflow/db  # Mount volume for SQLite database
    ports:
      - "8080:8080"
    entrypoint: >
      bash -c "
      airflow db init &&
      airflow users create -u admin -p admin -f admin -l user -r Admin -e admin@example.com &&
      exec airflow webserver
      "

  airflow-scheduler:
    build:
      context: airflow
    depends_on:
      - airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__FERNET_KEY=your_fernet_key
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/db:/opt/airflow/db  # Mount volume for SQLite database
    entrypoint: >
      bash -c "
      exec airflow scheduler
      "
